### ISSUE TITLE
Summon bugs

### ISSUE THREAD

**Issue by destdev** [Fluorohydride/ygopro#1880]
Since our update 8 days ago we have some summon bugs in our system:
1. The trigger effects of Psy Frame monsters in the hand don't trigger anymore. There's no error message or anything.
2. Dragon Buster Destruction Sword doesn't prevent the special summons from the extra deck.

As far as I can see there were no script changes for those cards, thus there is some core issue?

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/20909482/0862e5ce-bb97-11e6-9c05-db91542643ef.png)
![image](https://cloud.githubusercontent.com/assets/13391795/20909505/31d1bc28-bb97-11e6-9709-2118b72c064b.png)

cards with no tribute summon effect will be able to summon with both way, with no tribute

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/20909710/4391fb8e-bb98-11e6-8de6-3995677d72da.png)
you can select normal summon for _The Winged Dragon of Ra_ when you have only 2 tributes, but nothing will happen

**Comment by destdev** [comment]
oh, yes, forgot about those, we had that too
also we could no longer use the effect of Storm Forth and stuff like Sphere Mode couldn't be summoned to the opponents side of the field
we were able to get rid of that part of the problem, I don't know how though, you'd need to ask @sidschingis  about that one for details
if I understood him correctly our core should be up to date with the current one here, however we excluded
https://github.com/Fluorohydride/ygopro-core/commit/ec9d41a0af7b331ee2d52b982eebe9aa56f4cfad
https://github.com/Fluorohydride/ygopro-core/commit/108ab49da2fa669762e2a14050747b0b4b018c71
https://github.com/Fluorohydride/ygopro-core/commit/c670a7c870614425194df582ef7fd85d50095a1a

**Comment by mercury233** [comment]
@destdev thanks, after reverting those commits the two normal summon problem have gone.

**Comment by DailyShana** [comment]
@salix5 做大的修改请在充分测试后提交代码，你不止一次引起这种重大bug了

另外我不认为有必要更新summon proc，检查怪兽区格子数目应该由脚本负责
summon proc的设计就是为了统一处理各种非正规的召唤手续，并不局限于解放怪兽

**Comment by DailyShana** [comment]
_Dragon Buster Destruction Sword_: fixed in Fluorohydride/ygopro-scripts@ed3617c
`EFFECT_TYPE_EQUIP` means this effect only affect the equip target.

And I test the effect of _Psy Frame_ monsters and it works normally.

**Comment by destdev** [comment]
duh, I'm dumb, nvm the psyframes :/
should have tested with a bit more psyframes than 1 driver in the deck/hand when testing alpha at the report >.<
well, the only issues still running around is the stuff going on with custom normal summons with those commits up there

**Comment by destdev** [comment]
should be resolved with the revert, thanks
